# Generated by Django 4.1.5 on 2023-12-06 01:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha de Venta')),
                ('forma_pago', models.CharField(choices=[('Debito', 'Tarjeta de Debito'), ('Credito', 'Tarjeta de Credito'), ('Efectivo', 'Efectivo')], max_length=10, verbose_name='Tipo de Pago')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=3, verbose_name='Estado')),
                ('fecha_cita', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.cita', verbose_name=' Nombre Usuario')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
