# Generated by Django 4.1.5 on 2023-12-06 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arl', models.CharField(max_length=20, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombre Arl')),
                ('telefono_arl', models.CharField(max_length=10, validators=[usuarios.models.numeric_validator], verbose_name='Telefono Arl')),
                ('correo_arl', models.EmailField(max_length=50, verbose_name='Correo Arl')),
                ('fecha_inicioafi', models.DateField(verbose_name='Inicio De La Afiliación')),
                ('fecha_vencimientoafi', models.DateField(verbose_name='Vencimiento De La Afiliación')),
            ],
            options={
                'verbose_name_plural': 'arls',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombres')),
                ('apellidos', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Apellidos')),
                ('tipo_identificacion', models.CharField(choices=[('Cédula Ciudadania', 'Cédula Ciudadania'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extrangería', 'Cédula de Extrangería')], default='Cédula Ciudadania', max_length=18, verbose_name='Tipo de identificacion')),
                ('identificacion', models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificacion')),
                ('telefono', models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Telefono')),
                ('telefono2', models.CharField(blank=True, max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Segundo Telefono')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecanico', 'Mecanico')], default='Mecanico', max_length=13, verbose_name='Tipo Usuario')),
                ('nombres', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombres')),
                ('apellidos', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Apellidos')),
                ('tipo_identificacion', models.CharField(choices=[('Cédula Ciudadania', 'Cédula Ciudadania'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extrangería', 'Cédula de Extrangería')], default='Cédula Ciudadania', max_length=18, verbose_name='Tipo de identificacion')),
                ('identificacion', models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificacion')),
                ('telefono', models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Telefono')),
                ('telefono2', models.CharField(blank=True, max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Segundo Telefono')),
                ('nombreusuario', models.CharField(default='', max_length=20, verbose_name='Nombre De Usuario')),
                ('correo_personal', models.EmailField(default='', max_length=50, verbose_name='Correo Personal')),
                ('contraseña', models.CharField(default='', max_length=10, validators=[usuarios.models.validate_password, django.core.validators.RegexValidator(code='invalid_password', message='La contraseña solo puede contener letras y números.', regex='^[A-Za-z0-9]*$')], verbose_name='Contraseña')),
                ('confirmarcontraseña', models.CharField(default='', max_length=10, validators=[usuarios.models.validate_password, django.core.validators.RegexValidator(code='invalid_password', message='La contraseña solo puede contener letras y números.', regex='^[A-Za-z0-9]*$')], verbose_name='Confirmar Contraseña')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Registro')),
                ('rh', models.CharField(choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
                ('arl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.arl', verbose_name='ARL')),
            ],
            options={
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
